### ISSUE TITLE
sub/sup-scripts with mhchem

### ISSUE THREAD

**Issue by TomPcz** [dryabov/rmathbr#1]
Sub/sup-scripts in mhchem package are broken with rmathbr. Example:

```
\usepackage[version=4]{mhchem}
...
\ce{CO2}, \ce{H2O}
```

In this example, "2" should be `\scriptsize` subscript. If I load rmarhbr package, "2" is much bigger than it should be.

Moreover, we use this definition of `\_` and `\^` (text sub/sup-scripts):

```
\let\underscore\_                                       % underscore sign
\let\xor\^                                              % xor sign
\renewcommand\_[1]{\ifmmode _{\textnormal{#1}}\else\underscore#1\fi} %roman subscript
\renewcommand\^[1]{\ifmmode ^{\textnormal{#1}}\else\xor#1\fi} %roman superscript
```

This is also broken with rmathbr. In this example: `$x\_a y\^a$` the sub/sup-script "a" gets much bigger with rmathbr.

Could you please fix this?

**Comment by dryabov** [comment]
Fixed in 1.1
