### ISSUE TITLE
Sigma prime operator

### ISSUE THREAD

**Issue by ghost** [dryabov/rmathbr#2]
In "sigma prime" operator, defined as
\sideset{}{’}\sum
the prime sign is misplaced. This problem can be solved by redefining "sigma prime" operator as
\sideset{}{^\prime}\sum.

The above in Russian:
В операторе "сигма штрих", определённом как
\sideset{}{’}\sum
штрих не на том месте. Проблему можно решить, если переопределить оператор  "сигма штрих" так:
\sideset{}{^\prime}\sum.

**Comment by dryabov** [comment]
Fixed in 1.1
