### ISSUE TITLE
Vanishing spaces around = sign

### ISSUE THREAD

**Issue by ghost** [dryabov/rmathbr#3]
When TeX shrinks lines to fit them to the text width, sometimes spaces around = sign vanish, just like = is a symbol of binary operation. This happens because in the file rmathbr.sty (ver. 1.0.3) in lines 104-152 \brokenbin command is used everywhere. I guess that it will be correct to use \brokenbin command only for +, - and \* signs here, while for =, < and > signs \brokenrel command should be used instead of \brokenbin (I have tested, this can solve the problem).

The above in Russian:
Когда TeX сжимает строки, чтобы подогнать их под ширину текста, иногда пробелы вокруг знака = исчезают, как будто знак = это символ бинарной операции. Это происходит потому, что в файле rmathbr.sty (вер. 1.0.3) в строках 104-152 везде используется команда \brokenbin. Я думаю, что здесь будет правильно использовать команду \brokenbin только для знаков +, - и *, а для знаков =, < и > надо использовать команду \brokenrel вместо \brokenbin (я проверял, это может решить проблему).

**Comment by dryabov** [comment]
Fixed in 1.1
