### ISSUE TITLE
Symbols in n-th power roots may have larger size

### ISSUE THREAD

**Issue by Someone00OO** [dryabov/rmathbr#7]
В формулах вида
$\frac{\sqrt[3]{a^2}-\sqrt[3]{b^2}}{\sqrt[3]{a}-\sqrt[3]{b}}-\frac{a-b}{\sqrt[3]{a^2}-\sqrt[3]{b^2}}$,
$\frac{a^2\cdot\sqrt[4]{2}-2\sqrt{a}}{a\sqrt{2a}-\sqrt[4]{8a^4}}$,
$\sqrt{\frac{2a\sqrt[3]{a}}{(1+a)\sqrt[3]{1+a}}}\cdot\sqrt[3]{\frac{\log_216+\frac 8a+\frac 4{a^2}}{\sqrt{2}}}$,
содержащих дроби и корни с явным указанием степени, символы, стоящие под этими корнями, имеют бо́льший размер, чем следует. Это было бы желательно исправить, поскольку портит вёрстку.

**Comment by dryabov** [comment]
Fixed in 1.1
