### ISSUE TITLE
Конфликт с \mathchoice

### ISSUE THREAD

**Issue by numberZero** [dryabov/rmathbr#8]
При включённом rmathbr комадна `\mathchoice` выбирет первый вариант «display math» во внутритекстовых формулах $...$ и \(...\) вместо второго «inline math».

**Comment by dryabov** [comment]
Тут проблема не напрямую в `rmathbr`, а в пакете `mathstyle`, который он использует (там, судя по всему, примерно в прошлом году поменяли логику работы таким образом, что значение `\mathstyle` в тестовом режиме раньше было `1`, а теперь `2`, вот только значение по умолчанию не поменяли, но в https://github.com/wspr/breqn/blob/master/mathstyle.dtx ошибка уже исправлена, так что осталось дождаться, когда обновление подтянут основные дистрибутивы TeX). В качестве временного решения попробуйте добавить код
```tex
\chardef\mathstyle2
```
сразу после
```tex
\usepackage{rmathbr}
```

**Comment by dryabov** [comment]
Fixed in 1.1
